// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLS3kERF_j3lgsxxuk_uazRg_PqBrQuA',
    appId: '1:788985394590:web:a33bb2c2336b062e23928f',
    messagingSenderId: '788985394590',
    projectId: 'maps-87eda',
    authDomain: 'maps-87eda.firebaseapp.com',
    storageBucket: 'maps-87eda.appspot.com',
    measurementId: 'G-829NVVL9SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj-scyciOutxrLAnUIEtR_Euh9Cdji2j8',
    appId: '1:788985394590:android:ff1ec7464fd9b18523928f',
    messagingSenderId: '788985394590',
    projectId: 'maps-87eda',
    storageBucket: 'maps-87eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkLZNrILE2wDgBhaJEEVduIxxVZjZahc',
    appId: '1:788985394590:ios:3f70b88df3947fc023928f',
    messagingSenderId: '788985394590',
    projectId: 'maps-87eda',
    storageBucket: 'maps-87eda.appspot.com',
    iosBundleId: 'com.example.maps',
  );
}
